export enum EventLoginEnum {
   LOGIN = 'ON_PRESS_LOGIN',
}

export enum EventRequestErrorEnum {
   DEVELOPERS = 'ERROR_GET_DEVELOPERS',
   ME = 'ERROR_GET_ME_INFORMATION',
   LOGIN = 'ERROR_LOGIN_USER',
   REGISTER = 'ERROR_REGISTER_USER',
   PUBLICATONS = 'ERROR_GET_PUBLICATIONS',
}