export enum EventaAccountEnum {
   LOGIN = 'ON_PRESS_LOGIN',
}

export enum EventRequestErrorEnum {
   DEVELOPERS = 'ERROR_GET_DEVELOPERS',
   ME = 'ERROR_GET_ME_INFORMATION',
   LOGIN = 'ERROR_LOGIN_USER',
   REGISTER = 'ERROR_REGISTER_USER',
   PUBLICATONS = 'ERROR_GET_PUBLICATIONS',
   DEVELOPER = 'ERROR_GET_DEVELOPER_INFORMATION',
   PUBLICATION = 'ERROR_GET_PUBLICATION_INFORMATION',
   CREATE_PUBLICATION = 'ERROR_CREATE_A_PUBLICATION'
}